"""add city to company

Revision ID: e89c86ae7880
Revises: 8444d58c7d5c
Create Date: 2024-04-20 17:53:04.647283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89c86ae7880'
down_revision: Union[str, None] = '8444d58c7d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'city')
    # ### end Alembic commands ###
